"""Phase 1 data audit for FinNLP 2026 Subtask 3 (PolyFiQA).

Reads immutable raw files plus official HF manifests, verifies every structural
assumption programmatically, and writes reports/DATA_AUDIT.md and manifest CSVs.

Run:  python -m src.data_audit   (from finnlp2026_polyfiqa/)
"""
import hashlib
import io
import re
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "data" / "raw"
MAN = ROOT / "data" / "manifests"
REPORTS = ROOT / "reports"

PATHS = {
    "easy_train (supplied)": RAW / "public-00000-of-00001.parquet",
    "expert_test (drive participant)": RAW / "PolyFiQA_test_participant.parquet",
    "official_hf_train": MAN / "official_finnlp_train.parquet",
    "official_hf_test": MAN / "official_finnlp_test.parquet",
}

out = io.StringIO()


def w(line=""):
    print(line)
    out.write(line + "\n")


def sha(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def norm_ws(text: str) -> str:
    """Superficial whitespace normalization only (audit rule 1.5)."""
    return re.sub(r"\s+", " ", text).strip()


def split_query(q: str):
    """Split a query into (instruction, evidence, embedded_question_block).

    Verified structure (see DATA_AUDIT.md): instructions, then a literal
    'Context:' marker introducing the evidence (statements + multilingual
    news), then a trailing '\n\nQuestion:\n<question>\n\nAnswer:' block that
    repeats the row's `question` column. Only that trailing block varies
    across the 4 rows of one task_id.
    """
    c = q.find("Context:")
    qm = q.rfind("\nQuestion:")
    if c == -1 or qm == -1 or qm < c:
        return q, "", ""
    return q[:c], q[c:qm], q[qm:]


def file_sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def audit_frame(name: str, df: pd.DataFrame):
    w(f"\n### {name}")
    w(f"- rows: {len(df)}")
    w(f"- file: `{PATHS[name].name}` sha256 `{file_sha256(PATHS[name])[:16]}…`")
    w("\n| column | dtype | non-null | missing | unique |")
    w("|---|---|---|---|---|")
    for c in df.columns:
        w(f"| {c} | {df[c].dtype} | {df[c].notna().sum()} | {df[c].isna().sum()} | {df[c].nunique()} |")
    w(f"- duplicate full rows: {df.duplicated().sum()}")
    if "task_id" in df.columns:
        vc = df["task_id"].value_counts()
        w(f"- unique task_ids: {vc.size}; rows per task_id min/max: {vc.min()}/{vc.max()}")
    if "id" in df.columns:
        w(f"- id: count {len(df)}, unique {df['id'].nunique()}, "
          f"nulls {df['id'].isna().sum()}, duplicates {df['id'].duplicated().sum()}")


def main():
    dfs = {}
    for name, p in PATHS.items():
        if not p.exists():
            w(f"FATAL: missing expected file {p}")
            sys.exit(1)
        dfs[name] = pd.read_parquet(p)

    easy = dfs["easy_train (supplied)"]
    drive_test = dfs["expert_test (drive participant)"]
    hf_train = dfs["official_hf_train"]
    hf_test = dfs["official_hf_test"]

    w("# DATA AUDIT — FinNLP 2026 Subtask 3 (PolyFiQA)")
    w("\nGenerated by `python -m src.data_audit`. All findings derived "
      "programmatically from the files listed below; raw files are read-only.")

    w("\n## 1.1–1.2 Datasets, columns, dimensions")
    for name in PATHS:
        audit_frame(name, dfs[name])

    # ---- 1.3 question templates ----
    w("\n## 1.3 Exact question templates")
    for label, df in [("Easy/public", easy), ("Expert/test (drive)", drive_test),
                      ("Expert/test (official HF)", hf_test)]:
        qs = sorted(df["question"].unique())
        w(f"\n**{label}** — {len(qs)} distinct question strings:")
        for q in qs:
            n = (df["question"] == q).sum()
            w(f"- ({n} rows) {q}")

    # ---- 1.4 task_id overlap ----
    w("\n## 1.4 task_id overlap (Easy vs Expert)")
    e_ids, x_ids = set(easy.task_id), set(drive_test.task_id)
    w(f"- Easy task_ids: {len(e_ids)}; Expert task_ids: {len(x_ids)}; "
      f"intersection: {len(e_ids & x_ids)}")
    w(f"- Easy-only: {sorted(e_ids - x_ids) or 'none'}")
    w(f"- Expert-only: {sorted(x_ids - e_ids) or 'none'}")

    # ---- 1.5 / 1.6 context comparison ----
    w("\n## 1.5–1.6 Query and evidence-context comparison per task_id")
    w("\nMethod: each query = instruction + `Context:` evidence + trailing "
      "`Question:` block (verified to repeat the `question` column). For "
      "every row, hash (whitespace-normalized) the three parts. Within each "
      "task_id check that instruction+evidence are constant across its 4 "
      "rows; then compare Easy vs Expert per task_id.")
    for label, df in [("Easy", easy), ("Expert", drive_test)]:
        parts = df["query"].map(split_query)
        df["_instr_sha"] = [sha(norm_ws(p[0])) for p in parts]
        df["_evid_sha"] = [sha(norm_ws(p[1])) for p in parts]
        df["_q_in_query"] = [norm_ws(row.question) in norm_ws(p[2])
                             for p, row in zip(parts, df.itertuples())]
        const = (df.groupby("task_id")[["_instr_sha", "_evid_sha"]]
                 .nunique().le(1).all(axis=1))
        w(f"\n**{label}**: instruction+evidence constant within every "
          f"task_id: {const.all()} ({const.sum()}/{len(const)} task_ids); "
          f"embedded Question block matches `question` column in "
          f"{df['_q_in_query'].sum()}/{len(df)} rows")
    rows = []
    for tid in sorted(e_ids & x_ids):
        e_row = easy.loc[easy.task_id == tid].iloc[0]
        x_row = drive_test.loc[drive_test.task_id == tid].iloc[0]
        rows.append({
            "task_id": tid,
            "instr_equal": e_row["_instr_sha"] == x_row["_instr_sha"],
            "evidence_equal": e_row["_evid_sha"] == x_row["_evid_sha"],
            "easy_evidence_sha": e_row["_evid_sha"][:12],
            "expert_evidence_sha": x_row["_evid_sha"][:12],
        })
    cmp_df = pd.DataFrame(rows)
    w(f"\n- instruction block identical Easy vs Expert: {cmp_df.instr_equal.sum()}/{len(cmp_df)} task_ids")
    w(f"- evidence block identical Easy vs Expert:    {cmp_df.evidence_equal.sum()}/{len(cmp_df)} task_ids")
    w("\nPer-task detail:")
    w(cmp_df.to_markdown(index=False))
    cmp_df.to_csv(MAN / "easy_expert_context_comparison.csv", index=False)
    for df in (easy, drive_test):
        df.drop(columns=["_instr_sha", "_evid_sha", "_q_in_query"], inplace=True)

    # instruction-block diff sample (they may legitimately differ between tiers)
    ei = split_query(easy["query"].iloc[0])[0]
    xi = split_query(drive_test["query"].iloc[0])[0]
    if norm_ws(ei) != norm_ws(xi):
        w("\nInstruction blocks differ between tiers. Easy instruction:")
        w("```\n" + ei.strip()[:900] + "\n```")
        w("Expert instruction:")
        w("```\n" + xi.strip()[:900] + "\n```")
    else:
        w("\nInstruction blocks are identical between tiers:")
        w("```\n" + ei.strip()[:900] + "\n```")

    # ---- 1.9 official HF test vs drive participant test ----
    w("\n## 1.9 Official HF test vs Google Drive participant test")
    w(f"- row counts: HF {len(hf_test)} vs Drive {len(drive_test)}")
    w(f"- HF columns: {list(hf_test.columns)}")
    w(f"- Drive columns: {list(drive_test.columns)}")
    shared_cols = [c for c in drive_test.columns if c in hf_test.columns]
    same_order = all(
        (hf_test[c].reset_index(drop=True) == drive_test[c].reset_index(drop=True)).all()
        for c in shared_cols
    ) if len(hf_test) == len(drive_test) else False
    w(f"- shared columns {shared_cols} identical IN ROW ORDER: {same_order}")
    key = ["task_id", "question"]
    merged = hf_test.merge(drive_test, on=key, how="outer", indicator=True,
                           suffixes=("_hf", "_dr"))
    w(f"- outer join on {key}: both {sum(merged._merge == 'both')}, "
      f"HF-only {sum(merged._merge == 'left_only')}, Drive-only {sum(merged._merge == 'right_only')}")
    if "query_hf" in merged.columns:
        qeq = (merged.loc[merged._merge == "both", "query_hf"]
               == merged.loc[merged._merge == "both", "query_dr"]).all()
        w(f"- query strings identical for all joined rows: {qeq}")
    extra_cols = [c for c in hf_test.columns if c not in drive_test.columns]
    w(f"- columns only in official HF test: {extra_cols}")
    if "id" in hf_test.columns:
        w(f"- official id sample (first 5, in file order): {hf_test['id'].head().tolist()}")

    # official train vs supplied train
    w("\n## Supplied train vs official HF train")
    tr_equal = easy.reset_index(drop=True).equals(hf_train.reset_index(drop=True))
    w(f"- DataFrame.equals (all columns, all rows, in order): {tr_equal}")
    w(f"- file sha256 equal: "
      f"{file_sha256(PATHS['easy_train (supplied)']) == file_sha256(PATHS['official_hf_train'])}")

    # ---- 1.7 report grouping ----
    w("\n## 1.7 Report grouping")
    grp = (hf_test.groupby("task_id")
           .agg(rows=("question", "size"), distinct_questions=("question", "nunique"))
           .reset_index())
    grp["company"] = grp.task_id.str.split("_").str[0]
    w(grp.to_markdown(index=False))

    # ---- manifests ----
    tm = easy.copy()
    tm["query_sha256"] = tm["query"].map(lambda q: sha(norm_ws(q)))
    tm["answer_words"] = tm["answer"].str.split().str.len()
    tm[["task_id", "question", "query_sha256", "answer_words"]].to_csv(
        MAN / "train_manifest.csv", index=False)
    sm = hf_test.copy()
    sm["query_sha256"] = sm["query"].map(lambda q: sha(norm_ws(q)))
    keep = [c for c in ["id", "task_id", "question", "query_sha256"] if c in sm.columns]
    sm[keep].to_csv(MAN / "test_manifest.csv", index=False)
    w("\nManifests written: data/manifests/train_manifest.csv, test_manifest.csv, "
      "easy_expert_context_comparison.csv")

    REPORTS.mkdir(exist_ok=True)
    (REPORTS / "DATA_AUDIT.md").write_text(out.getvalue(), encoding="utf-8")
    w("\nReport written: reports/DATA_AUDIT.md")


if __name__ == "__main__":
    main()
