"""Build System D retrieval chunk collections from the supplied contexts.

Run: python -m src.retrieval.build_chunks

Reads ONLY the `task_id` and `query` columns of the two supplied parquet
files (gold/reference answers are never loaded), parses each task's shared
evidence context once, and writes two JSONL chunk collections per dataset
plus a chunking report. No model/API calls are made.

Outputs (all new files; nothing in System C is touched):
    data/processed/rag_chunks/<dataset>.news.jsonl
    data/processed/rag_chunks/<dataset>.financial_statements.jsonl
    data/processed/rag_chunks/chunking_summary.json
    reports/RAG_CHUNKING.md
"""
from __future__ import annotations

import json
import statistics
import sys
from collections import Counter
from pathlib import Path

import pandas as pd
import regex as re

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from src.retrieval.context_parser import parse_context
from src.retrieval.chunker import Chunk, chunk_news_section, chunk_statement_block

DATASETS = {
    "easy_train": ROOT / "data/raw/public-00000-of-00001.parquet",
    "expert_test": ROOT / "data/raw/PolyFiQA_test_participant.parquet",
}
OUT_DIR = ROOT / "data/processed/rag_chunks"

_SCRIPTS = {
    "Han": re.compile(r"\p{Han}"),
    "Kana": re.compile(r"[\p{Hiragana}\p{Katakana}]"),
    "Greek": re.compile(r"\p{Greek}"),
    "Latin": re.compile(r"\p{Latin}"),
}


def scripts_in(text: str) -> list[str]:
    return [name for name, rx in _SCRIPTS.items() if rx.search(text)]


def build_dataset(name: str, path: Path):
    # Load ONLY task_id + query: the answer column (when present) is never read.
    df = pd.read_parquet(path, columns=["task_id", "query"])
    df = df.drop_duplicates("task_id", keep="first")

    news: list[Chunk] = []
    fs: list[Chunk] = []
    loss_failures: list[str] = []

    for _, row in df.iterrows():
        task_id, q = row["task_id"], row["query"]
        parsed = parse_context(task_id, q)  # raises if any context text unaccounted for

        for sec in parsed.news_sections:
            cs = chunk_news_section(task_id, name, sec.language_name,
                                    sec.language, sec.body.text, sec.body.start)
            if "".join(c.text for c in cs) != sec.body.text:
                loss_failures.append(f"{task_id}:news:{sec.language}")
            for c in cs:
                if q[c.char_start:c.char_end] != c.text:
                    loss_failures.append(f"{task_id}:news-span:{c.chunk_id}")
            news.extend(cs)

        for ti, blk in enumerate(parsed.statement_blocks):
            cs = chunk_statement_block(task_id, name, ti, blk.text, blk.start)
            if "\n".join(c.text for c in cs) != blk.text:
                loss_failures.append(f"{task_id}:fs:t{ti}")
            for c in cs:
                if q[c.char_start:c.char_end] != c.text:
                    loss_failures.append(f"{task_id}:fs-span:{c.chunk_id}")
            fs.extend(cs)

    return df["task_id"].tolist(), news, fs, loss_failures


def write_jsonl(path: Path, chunks: list[Chunk]) -> None:
    with path.open("w", encoding="utf-8") as f:
        for c in chunks:
            f.write(json.dumps(c.to_dict(), ensure_ascii=False) + "\n")


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    report: list[str] = ["# RAG CHUNKING REPORT — System D data layer",
                         "", "Generated by `python -m src.retrieval.build_chunks`. "
                         "No API calls; answers never read; System C untouched.", ""]
    summary: dict = {}

    for name, path in DATASETS.items():
        task_ids, news, fs, losses = build_dataset(name, path)
        write_jsonl(OUT_DIR / f"{name}.news.jsonl", news)
        write_jsonl(OUT_DIR / f"{name}.financial_statements.jsonl", fs)

        per_task = Counter(c.task_id for c in news + fs)
        counts = sorted(per_task.values())
        lang_counter = Counter(c.language for c in news)
        stmt_counter = Counter(c.statement_type for c in fs)
        ids = [c.chunk_id for c in news + fs]
        assert len(ids) == len(set(ids)), "chunk_id collision"

        script_check = {}
        for lang in sorted(set(c.language for c in news)):
            sample = next(c for c in news if c.language == lang)
            script_check[lang] = scripts_in(sample.text)

        summary[name] = {
            "file": str(path.name),
            "task_ids": len(task_ids),
            "news_chunks": len(news),
            "financial_statement_chunks": len(fs),
            "chunks_per_task_min": counts[0],
            "chunks_per_task_median": statistics.median(counts),
            "chunks_per_task_max": counts[-1],
            "news_chunks_by_language": dict(lang_counter),
            "fs_chunks_by_statement_type": dict(stmt_counter),
            "text_loss_failures": losses,
        }

        report += [f"## {name} ({path.name})", "",
                   f"- task_ids processed: {len(task_ids)}",
                   f"- news chunks: {len(news)} (by language: {dict(lang_counter)})",
                   f"- financial-statement chunks: {len(fs)} "
                   f"(by type: {dict(stmt_counter)})",
                   f"- chunks per task_id: min {counts[0]} / median "
                   f"{statistics.median(counts)} / max {counts[-1]}",
                   f"- scripts observed per language sample: {script_check}",
                   f"- text lost during chunking: "
                   f"{'NONE' if not losses else losses}", ""]

        rows = ["| task_id | news | fs | total |", "|---|---|---|---|"]
        nt = Counter(c.task_id for c in news)
        ft = Counter(c.task_id for c in fs)
        for t in task_ids:
            rows.append(f"| {t} | {nt[t]} | {ft[t]} | {per_task[t]} |")
        report += rows + [""]

    (OUT_DIR / "chunking_summary.json").write_text(
        json.dumps(summary, indent=2, ensure_ascii=False), encoding="utf-8")
    report_path = ROOT / "reports/RAG_CHUNKING.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text("\n".join(report), encoding="utf-8")
    print("\n".join(report))
    print(f"Wrote {OUT_DIR} and reports/RAG_CHUNKING.md")


if __name__ == "__main__":
    main()
